#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from extern.embeddedimage import PyEmbeddedImage

Disconnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAohJ"
    "REFUOI2Vkj1PFFEUht/ZOzPOwBpB3fClNgYKCws/ChoKoiZYWJjYWJkQC0IstDKhMEZbjQkJ"
    "If4AYrCw0AYN2VCIBCQqUVlUCCzs7Dczs7sz9965d3Zs1LhxMXrq931ynpOj4D/n3pO1AcbE"
    "bC2QglJ+WflbOJmM1C/S6g5o1MNFkPACcUFBNGpqEbiQWFkvU3Wv8vR82kxVsrNS1vtFJBHW"
    "JVp1BXGDgAUCeZtjt+arewKKNrlhaPX+w20EPIjARATKBbK7HnQCrO/YYC4731Th8av1vhLL"
    "rh5tPRajPETJ9UG5gM8F9hsE6byLtfXSxOvJK6MNG0zPp03HVacY/XhRHpqNbRQH0I7jMPUY"
    "8jYHZQGIoiFnVSCrbAYAfgHuJCO15FgfTK3eq6knUNnMhOLIHFlYFmHC6CBxQ0Vhl0MngFfx"
    "EHheEQBiPwHtVaubC9EbN2PQ1DpajH5SWTklQiHGUulvYdpy0NaiwmMcvu2D11imAeBLvycI"
    "BCgX2C7WoOsKzHifZqBw/+y5RZIvpmBZDjZTOfhO5WtC2FaDgu/xRAyAzxT4NEDZkTjQQtDR"
    "flrNvc/hzNAqXk5y6bvKiwrF1U8Ld2UDwPWC4a42DT4NUKMclAkUHQFDI0A0iOVnSRlCnvyc"
    "vL36++FVABgZX7plarikqzHkbA+tBoFGIuzTFASBwFa6jILVNfbu+UhDGQDU64+Wbhq68qBV"
    "j4GyABqJsJVxUSpVQasMrEpBK+yNadPxZj+j1hh72HkwjigKsZ2vYttyYBdqE1LKmZCxIpcs"
    "k/Bta+6H8x8At0qRzoYgiJDZcWCX3cHFqWvJZuGmAFalnRu7bk76ggqfDr19Ojz3r2UA+A5Y"
    "z3SvHbteLQAAAABJRU5ErkJggg==")
getDisconnectData = Disconnect.GetData
getDisconnectImage = Disconnect.GetImage
getDisconnectBitmap = Disconnect.GetBitmap

#----------------------------------------------------------------------
Connect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAr1J"
    "REFUOI2FkktoFGkUhU+9urrS6dGEpMVEHYY4UUFwIS6iLgRH0NWAoKC7yCxEmNUQHBwYcSOu"
    "dOHKnW5ctMFHUIlxgo8hj9VEMIpRY0zHTtOdTlWq+q//Vf/fPQtRBNN61vd+nHPPNfAdPXrU"
    "sAt20JVw2S256iRS9lKZnKdUjM4VzF+Nby3nxwse5d6o1qpPJhqJUtBKwnNNFCo1vF0kw/a3"
    "ADXq/u7aum9tiwmR1CGkASZMhLFA2jHgh+H+pg7y+elUMfVDuL7NSTMhUI04mJCIuULWs/Dq"
    "/TLmF4IBsxng6NHtMqT04vtKhJhLuDawQgTCGgWhDH6VQEb09VcRrv3rb9Jvbv8tpbROHt/a"
    "/9ulCRYx9df6tlQ6mzZRqnJYpgsSEsgwXvocIT9e8AhLX1fhwqGNXsV1HAdTU1NXBwYG+n85"
    "fX+vivnIhnVZL9PqQCQJno+/AyPsR+tTVSVBp10be5x0xp4tLKqMSc1SqfSso6Pj7s+Zam0u"
    "yA1XSv6xRqPulOd9BJWVNzkdXjAA4MrD4iYp6vNd7Q6ETFBe4ZifnZG+zB5oL9/qp5T2CSH2"
    "TZV3bVZSPtANNRIz6/iHyT+YDQBhTXabqIPxBorLFJm0gZb27lRpZvqfnp4eJ5fLYXBw8PGW"
    "7JPdLxZ3bpsZ+7PwKboNAHHMOy0LiHkDhHJUggRrWmxs/GmzM/b8KXaQdxBCTAwNDfnADf/L"
    "o390QFhva4sJyoGICjAuUfYl0rYFb8NO3JscT5Tbc2q1uq0j+emUXiKjubWuFcUcKcuAbQG2"
    "aUDXNQpzS1he1mf+u3P2yWoA254NiJexHK0UYiawUAxRC2IwwsGJAI3iiZCoy80ezl6J6aiF"
    "1MGX1Ro+LPiJpOyMlslrULkktC52JsHii8lzqikgiMPDUdm4qZnYH4lU68sbJ2Sz4dX0P7YL"
    "jqnaHUJ7AAAAAElFTkSuQmCC")
getConnectData = Connect.GetData
getConnectImage = Connect.GetImage
getConnectBitmap = Connect.GetBitmap
